java_library(
    name = "examplelib",
    srcs = ["HelloLib.java"],
    visibility = ["//visibility:public"],
    runtime_deps = [":examplesublib"],
)

java_library(
    name = "examplesublib",
    srcs = ["HelloSubLib.java"],
    visibility = ["//visibility:public"],
)
